var question = {"groupe1": ["Vous aimez avoir des activités à l'exterieur, travailler en plein air ?",
                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                            "Vous aimez travailler avec des chiffres ?"],
                "groupe2": ["Groupe 2 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe3": ["Groupe 3 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe4": ["Groupe 4 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe5": ["Groupe 5 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe6": ["Groupe 6 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe7": ["Groupe 7 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe8": ["Groupe 8 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe9": ["Groupe 9 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe10": ["Groupe 10 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe11": ["Groupe 11 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"],
                "groupe12": ["Groupe 12 ?",
                                            "Vous aimez élargir vos connaissances par l'étude, pouvoir approfondir un sujet ?",
                                            "Vous aimez travailler de facon indépendante, sans methode ni objectif structurés ?",
                                            "Vous aimez travailler avec d'autres personnes pour les informer ?",
                                            "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d'argent ?",
                                            "Vous aimez travailler avec des chiffres ?"]




                }
