-- Remplissage de la base de données

-- Table 'profile'
INSERT INTO profile (type, url_description)
VALUES ('R', '/RIASEC/realiste.pdf'),
       ('I', '/RIASEC/investigatif.pdf'),
       ('A', '/RIASEC/artistique.pdf'),
       ('S', '/RIASEC/social.pdf'),
       ('E', '/RIASEC/entrepreneur.pdf'),
       ('C', '/RIASEC/conventionnel.pdf');

-- Table 'proposition'
INSERT INTO proposition (ID_proposition, groupe, label_proposition, profile)
VALUES ('A', 1, 'Vous aimez avoir des activités à l\'extérieur, travailler en plein air', 1),
       ('B', 1, 'Vous aimez élargir vos connaissances par l\'étude, pouvoir approfondir un sujet', 2),
       ('C', 1, 'Vous aimez travailler de façon indépendante, sans méthode ni objectif structurés', 3),
       ('D', 1, 'Vous aimez travailler avec d\'autres personnes pour les informer', 4),
       ('E', 1, 'Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d\'argent', 5),
       ('F', 1, 'Vous aimez travailler avec des chiffres', 6),
       ('A', 2, 'Vous admirez les personnes qui travaillent pour soigner les autres', 4),
       ('B', 2, 'Vous aimez une organisation claire et bien définie', 6),
       ('C', 2, 'Vous aimez contribuer à atteindre les objectifs d\'une organisation', 5),
       ('D', 2, 'Vous aimez le sport, vous dépenser physiquement', 1),
       ('E', 2, 'Vous aimez étudier les choses, les phénomènes ou les comportements', 2),
       ('F', 2, 'Vous admirez les personnes qui ont des capacités artistiques', 3),
       ('A', 3, 'Vous aimez travailler avec d\'autres personnes pour les former, les entraîner', 4),
       ('B', 3, 'Vous aimez les changements ou les situations imprévues', 3),
       ('C', 3, 'Vous aimez ne faire qu\'une seule chose à la fois et vous ne vous laissez pas distraire', 6),
       ('D', 3, 'Vous aimez donner des ordres ou consignes et organiser l\'activité des autres', 5),
       ('E', 3, 'Vous aimez tirer vos propres conclusions de l\'analyse d\'une situation donnée', 2),
       ('F', 3, 'Vous aimez conduire des véhicules ou faire fonctionner des machines', 1),
       ('A', 4, 'Vous aimez fabriquer ou réparer des objets', 1),
       ('B', 4, 'Vous aimez ne pas savoir précisément ce que vous avez à faire', 3),
       ('C', 4, 'Vous aimez mettre en œuvre des « bonnes pratiques » acquises par l\'expérience', 6),
       ('D', 4, 'Vous aimez faire preuve d\'initiative et prendre des décisions rapides', 5),
       ('E', 4, 'Vous aimez écouter, dialoguer, essayer de comprendre les autres', 4),
       ('F', 4, 'Vous aimez vous fier à votre jugement pour décider comment faire les choses', 2),
       ('A', 5, 'Vous aimez faire plusieurs activités en même temps, ou passer d\'une action à l\'autre', 3),
       ('B', 5, 'Vous aimez décider de ce qui doit être fait', 5),
       ('C', 5, 'Vous aimez rencontrer des gens nouveaux', 4),
       ('D', 5, 'Vous aimez vérifier une conclusion par des tests ou des informations complémentaires', 2),
       ('E', 5, 'Vous aimez appuyer vos conclusions sur des bases déjà prouvées', 6),
       ('F', 5, 'Vous aimez bricoler, utiliser des outils tels que tournevis, ciseaux, pinces, etc...', 1),
       ('A', 6, 'Vous aimez résoudre les problèmes de façon rationnelle, étape par étape', 2),
       ('B', 6, 'Vous aimez la nature, les plantes, les animaux...', 1),
       ('C', 6, 'Vous aimez respecter les valeurs que vous vous êtes fixées', 6),
       ('D', 6, 'Vous aimez faire un travail en commun avec d\'autres', 4),
       ('E', 6, 'Vous aimez relever des défis', 5),
       ('F', 6, 'Vous aimez vous fier à votre intuition pour prendre des décisions', 3),
       ('A', 7, 'Vous aimez convaincre les autres d\'agir d\'une certaine façon', 5),
       ('B', 7, 'Vous aimez résoudre un problème sans avoir recours à une méthode logique', 3),
       ('C', 7, 'Vous aimez prendre une décision après une réflexion, si possible logique', 2),
       ('D', 7, 'Vous aimez suivre attentivement un plan pour atteindre le meilleur résultat possible', 6),
       ('E', 7, 'Vous aimez écouter les autres et les conseiller sur la façon de résoudre leurs problèmes', 4),
       ('F', 7, 'Vous aimez trouver une solution concrète, réaliste et simple aux problèmes', 1),
       ('A', 8, 'Vous aimez concevoir ou améliorer les méthodes de travail', 2),
       ('B', 8, 'Vous aimez utiliser votre « bon sens »', 1),
       ('C', 8, 'Vous aimez rendre service, venir en aide à d\'autres personnes', 4),
       ('D', 8, 'Vous aimez répondre aux objections de vos interlocuteurs pour mieux les convaincre', 5),
       ('E', 8, 'Vous aimez montrer votre originalité', 3),
       ('F', 8, 'Vous aimez travailler avec soin pour obtenir un résultat parfait', 6),
       ('A', 9, 'Vous aimez ou aimeriez animer des activités collectives, associatives...', 4),
       ('B', 9, 'Vous aimez ou aimeriez étudier la physique, la biologie, ou la technologie', 2),
       ('C', 9, 'Vous aimez démonter un appareil pour le réparer vous-même', 1),
       ('D', 9, 'Vous aimez discuter avec un commerçant pour obtenir des réductions de prix', 5),
       ('E', 9, 'Vous aimez exprimer vos idées, vos points de vue ou vos émotions', 3),
       ('F', 9, 'Vous aimez rédiger un résumé, une lettre, un compte-rendu', 6),
       ('A', 10, 'Vous aimez faire face aux situations urgentes ou imprévues', 5),
       ('B', 10, 'Vous aimez vous occuper de démarches administratives ou d\'ordre juridique', 6),
       ('C', 10, 'Vous aimez ou aimeriez faire des reportages, écrire des articles, etc...', 4),
       ('D', 10, 'Vous aimez chercher à comprendre et à expliquer le pourquoi des choses et des êtres', 2),
       ('E', 10, 'Vous aimez imaginer des solutions qui sortent de l\'ordinaire', 3),
       ('F', 10, 'Vous aimez ou aimeriez utiliser un objet que vous avez fabriqué vous-même', 1),
       ('A', 11, 'Vous aimez apprendre aux autres ce que vous savez', 4),
       ('B', 11, 'Vous aimez collectionner des choses : timbres, cartes postales, pierres, etc...', 1),
       ('C', 11, 'Vous aimez passer une grande partie de votre temps sur des documents écrits', 6),
       ('D', 11, 'Vous aimez ou aimeriez vendre des produits ou services', 5),
       ('E', 11, 'Vous aimez vous servir d\'un microscope ou autre appareil de mesure...', 2),
       ('F', 11, 'Vous aimez ou aimeriez avoir des loisirs créatifs : peinture, musique...', 3),
       ('A', 12, 'Vous aimez classer, ordonner des documents ou des objets', 6),
       ('B', 12, 'Vous aimez conduire une discussion, un débat', 5),
       ('C', 12, 'Vous aimez échanger des idées avec les autres', 4),
       ('D', 12, 'Vous aimez que ce que vous faites débouche sur des résultats concrets', 1),
       ('E', 12, 'Vous aimez ou aimeriez mettre au point et réaliser des expériences scientifiques', 2),
       ('F', 12, 'Vous aimez étudier ou inventer plusieurs solutions pour répondre à un problème', 3);

INSERT INTO department (label_department)
VALUES ('ENR'),
       ('IG'),
       ('GBA'),
       ('MAT'),
       ('MI'),
       ('MEA'),
       ('STE');
